{% set name = "ecell4_base" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ecell/{{ name }}/releases/download/v{{ version }}/ecell4_base.tar.gz
    sha256: e86029d807f6b2f79070ee7d4f3659e9daaeef6558212e78dbf01459a0330905
    patches:
      - 3713c26ca11e60b1d429a624df26e8277be6f634.patch

build:
  number: 1
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_{{ target_platform }}  # [win]
    - cmake
  host:
    - python
    - setuptools
    - pip
    - pybind11
    - hdf5 =1.10.5
    - gsl
    - boost
  run:
    - gsl
    - hdf5 =1.10.5
    - zlib
    - python

test:
  imports:
    - ecell4_base.core
    - ecell4_base.bd
    - ecell4_base.egfrd
    - ecell4_base.gillespie
    - ecell4_base.meso
    - ecell4_base.ode
    - ecell4_base.sgfrd
    - ecell4_base.spatiocyte

about:
  home: https://github.com/ecell/ecell4_base
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An integrated software environment for multi-algorithm, multi-timescale, multi-spatial-representation simulation

extra:
  recipe-maintainers:
    - kozo2
    - ToruNiina
    - 0ncorhynchus
